Include metadata in junit xml results as property tags
pytest-dev/pytest-metadata pull request #31
Opened 2020-10-25 04:49 UTC by sanga

By adding an autoused session fixture that calls record_testsuite_property.

A couple of questions about this.

To my understanding `<property>` tags aren't supported in xunit1 format - however this feels like something that pytest itself should be looking after rather than checking that in this plugin (i.e. `record_testsuite_property` should be a null op in that case, or raise or something).

This only handles the session-level metadata. TBH, that's all I need and it's useful in itself.

I suppose that this could/should be noted in the docs somewhere (should it?). I couldn't decide where to reasonably mention this.

2020-10-25 04:50 UTC, sanga commented
This would close #16 btw (at least partially). I finally got around to it (just from my personal account)

2020-11-25 08:51 UTC, timsampsoncujo commented
ping @BeyondEvil any interest in this?

2020-11-25 08:54 UTC, BeyondEvil commented
Sorry, I've totally missed this @sanga 

Thanks for pinging me @timsampsoncujo !

2020-11-25 20:25 UTC, BeyondEvil requested changes

2020-11-26 04:06 UTC, sanga commented on pytest_metadata/plugin.py
> +@pytest.fixture(scope="session", autouse=True)
Yeah, I don't like this either but this was the only way to have the metadata be added to the junit xml automatically (which I think it should be). To me it feels like pytest should have a way of doing this without leaking the details to the user. TL/DR I don't like autouse here either and will remove it.

2020-11-26 04:06 UTC, sanga commented on pytest_metadata/plugin.py
> +    for k, v in md.items():
Sure. Fix incoming.

2020-11-26 04:12 UTC, sanga commented
Comments should now be addressed.

2020-11-26 11:15 UTC, BeyondEvil approved these changes

2020-11-26 11:17 UTC, BeyondEvil requested changes
This looks great!

Can you address the failing tests and rebase with master branch?

Also, can you add usage etc. to the docs so we don't hide this functionality?

Please also update `CHANGES.rst`, you can put `1.11.0 (unreleased)` as the header.

🙏

2020-11-27 06:55 UTC, sanga commented
Comments should be addressed now.

2020-11-27 13:06 UTC, BeyondEvil approved these changes

2020-11-27 13:06 UTC, BeyondEvil commented
Excellent! Great job! 💪

2020-11-27 13:06 UTC, merged